[keyboard]
name = "corne-rmk"
product_name = "corne"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "rmk"
chip = "nrf52840"

[layout]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true
rows = 4
cols = 10
layers = 9
matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4) (0,5) (0,6) (0,7) (0,8) (0,9)
(1,0) (1,1) (1,2) (1,3) (1,4) (1,5) (1,6) (1,7) (1,8) (1,9)
(2,0) (2,1) (2,2) (2,3) (2,4) (2,5) (2,6) (2,7) (2,8) (2,9)
            (3,2) (3,3) (3,4) (3,5) (3,6) (3,7) 
"""

[[layer]]
name = "BaseLayer" #optional name for the layer
keys = """
Q W F P B J L U Y A
MT(A, LGui) MT(R, LAlt) MT(S, LCtrl) MT(T, LShift) G M MT(N, RShift) MT(E, RCtrl) MT(I, RAlt) MT(O, RGui)
Z X C D V K H Dot A A
    LT(3, Esc) LT(1, Space) LT(2, Tab) LT(5, Enter) LT(4, Backspace) LT(6, Delete)
"""

[[layer]]
name = "Nav" #optional name for the layer
keys = """
_    _    _     _      _ Again    Paste      Copy   Cut      Undo
LGui LAlt LCtrl LShift _ CapsLock Left       Down   Up       Right
_    _    _     _      _ Insert    Home      PageUp PageDown End
          A     A      A Enter     Backspace Delete
"""

[[layer]]
name = "Mouse" #optional name for the layer
keys = """
_    _    _     _      _ Again    Paste      Copy   Cut      Undo
LGui LAlt LCtrl LShift _ _ MouseLeft MouseDown MouseUp MouseRight
_    _    _     _      _ _ _ _ _ _
          _ _ _ MouseBtn1 MouseBtn3 MouseBtn2
"""

[[layer]]
name = "Media" #optional name for the layer
keys = """
_    _    _     _      _ _ _       _    _    _
LGui LAlt LCtrl LShift _ _ RShift RCtrl RAlt RGui
_    _    _     _      _ _ _      _     _    _
          _ _ _ _ _ _
"""

[[layer]]
name = "Num" #optional name for the layer
keys = """
_ Kc7 Kc8 Kc9 _ _ _       _    _    _
_ Kc4 Kc5 Kc6 _ _ RShift RCtrl RAlt RGui
_ Kc1 Kc2 Kc3 _ _ _      _     _    _
          _ Kc0 _ _ _ _
"""

[[layer]]
name = "Sym" #optional name for the layer
keys = """
_    _    _     _      _ _ _       _    _    _
LGui LAlt LCtrl LShift _ _ RShift RCtrl RAlt RGui
_    _    _     _      _ _ _      _     _    _
          _ _ _ _ _ _
"""

[[layer]]
name = "Fun" #optional name for the layer
keys = """
F12 F7 F8 F9 _ _ _ _ _ _
F11 F4 F5 F6 _ _ RShift RCtrl RAlt RGui
F10 F1 F2 F3 _ _ _ _ _ _
       Esc Space Tab _ _ _
"""

[[layer]]
name = "Game" #optional name for the layer
keys = """
Tab Q W E R T Y U I O 
Shift A S D F G H J K L 
LCtrl Z X C V B N M A A 
       Esc Space M _ _ _
"""

[[layer]]
name = "Game2" #optional name for the layer
keys = """
_ Kc7 Kc8 Kc9 _ _ _       _    _    _
Kc0 Kc4 Kc5 Kc6 _ _ RShift RCtrl RAlt RGui
_ Kc1 Kc2 Kc3 _ _ _      _     _    _
          _ _ _ _ _ _
"""

[ble]
enabled = true

[behavior]
tap_hold = { enable_hrm = true, prior_idle_time = "100ms", hold_timeout = "200ms", post_wait_time = "25ms"}

[split]
connection = "ble"

[storage]
enabled = true
clear_storage = true

[split.central]
rows = 4
cols = 5
row_offset = 0
col_offset = 0
ble_addr = [0x18, 0xe2, 0x21, 0x80, 0xc0, 0xc7]
[split.central.matrix]
input_pins = ["P0_22", "P0_24", "P1_00", "P0_11"]
output_pins = ["P0_29", "P0_02", "P1_15", "P1_13", "P1_11"]

[[split.peripheral]]
rows = 4
cols = 5
row_offset = 0
col_offset = 5
ble_addr = [0x7e, 0xfe, 0x73, 0x9e, 0x66, 0xe3]
[split.peripheral.matrix]
input_pins = ["P0_22", "P0_24", "P1_00", "P0_11"]
output_pins = ["P1_11", "P1_13", "P1_15", "P0_02", "P0_29"]

# [[split.peripheral]]
# rows = 2
# cols = 1
# row_offset = 2
# col_offset = 2
# serial = [{ instance = "UART0", tx_pin = "PIN_0", rx_pin = "PIN_1" }]
# input_pins = ["PIN_9", "PIN_11"]
# output_pins = ["PIN_10"]
